// <auto-generated />
namespace RestaurantReview.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedatasize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedatasize));
        
        string IMigrationMetadata.Id
        {
            get { return "201805292313318_change data size"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
